# Table of Contents
# -----------------

toc:
  - head: /index.html
    body: []
  - head: /intro/index.html
    body:
      - /intro/type-class.html
      - /intro/scalaz.html
      - /intro/equal.html
      - /intro/summary.html
  - head: /monoids/index.html
    body:
      - /monoids/scalaz.html
      - /monoids/instance-selection.html
      - /monoids/pygmy-hadoop.html
  - head: /functors/index.html
    body:
      - /functors/scalaz.html
  - head: /monads/index.html
    body:
      - /monads/scalaz.html
      - /monads/either.html


# Jekyll Configuration
# --------------------

url         : http://underscore.io

source      : src/pages
posts       : src/posts
layouts     : src/layouts
includes    : src/includes

destination : essential-scalaz
plugins     : jekyll_plugins

keep_files  : [ 'css', 'js', 'images' ]

permalink   : /:categories/:year/:month/:day/:title

safe        : false
highlighter : pygments
markdown    : kramdown

kramdown:
  parse_block_html: true